# Generated by Django 3.1.4 on 2020-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201220_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='OS3LEVJYXI', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='0JWR4962YO', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='G9TTTFU2I6', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='DCUDRO93OU', editable=False, max_length=10),
        ),
    ]
