# Generated by Django 3.1.4 on 2020-12-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201220_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='notes',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='5PNYWEKZJT', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='ZEMMLEB5QT', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='ZQYVEKRW2C', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='O2XPUFA2V4', editable=False, max_length=10),
        ),
    ]
