# Generated by Django 3.1.4 on 2020-12-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201221_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='LXVDRMMEGP', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='9YPLZGRERC', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='BRCSAX5DYP', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='0VNDU7VKKQ', editable=False, max_length=10),
        ),
    ]
