# Generated by Django 3.1.4 on 2020-12-22 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201221_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='LU2IBLX0BX', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='BT0KUPHVY7', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='LPTVM6QRAQ', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='KGQ8KMAQPU', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
