# Generated by Django 3.1.4 on 2020-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201222_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='recurring',
            field=models.CharField(default='one time', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='DFU1UAHI9C', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='EQMCLECZMX', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='COTJX6YIM6', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='CH5YGJAW84', editable=False, max_length=10),
        ),
    ]
