# Generated by Django 3.1.4 on 2020-12-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20201222_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='is_pickedup',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='picked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='DT84IC9YFD', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='DBVQOZV2O4', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='KGGRYUYOF4', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='687NIVCRZV', editable=False, max_length=10),
        ),
    ]
