# Generated by Django 3.1.4 on 2020-12-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20201222_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='commercial',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='industrial',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default='YIPBMAETU3', editable=False, max_length=10),
        ),
    ]
