# Generated by Django 3.1.4 on 2020-12-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20201223_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='QABJJN9IAG', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='HBJKXZAHWB', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='E5V88MOCQF', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='CYNJ8AYUPQ', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default='OXVMD9MVGR', editable=False, max_length=10),
        ),
    ]
