# Generated by Django 3.1.4 on 2020-12-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20201223_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='NT918E0BGD', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='DCCDV4AX4W', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='VOYMNSDRKW', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='FQF4LRHQYK', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(default='D4TRTWPA9T', editable=False, max_length=10),
        ),
    ]
