# Generated by Django 3.1.4 on 2020-12-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20201223_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='bulk',
            name='customer_id',
            field=models.CharField(default='8KC7PP0S2G', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='commercial',
            name='customer_id',
            field=models.CharField(default='4878QUSH7M', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_id',
            field=models.CharField(default='SBU0C9JJUU', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='industrial',
            name='customer_id',
            field=models.CharField(default='FTLZP2TRIU', editable=False, max_length=10),
        ),
    ]
